default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306 # コンテナ内のMySQLがリッスンするポート

# 注意:
# Docker Composeでは、同じComposeファイル内のサービス間で通信する際、
# サービス名をホスト名として使用します。
# そのため、ホストマシンからMySQLに接続する際はホストのポート3307を使用しますが、
# コンテナ間の通信ではMySQLのデフォルトポート3306を使用します。

development:
  <<: *default
  host: db
  database: backend_development
  password: password

test:
  <<: *default
  host: db
  database: backend_test
  password: password
