version: '3'
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: bash -c "bundle exec rails s -b '0.0.0.0'"
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./backend:/backend
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
volumes:
  mysql_data:
