source "https://rubygems.org"

ruby "3.2.4"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# MySQLに接続するためのgem
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem） [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎のドメイン管理に使用
gem "config"

# 環境変数を設定
gem "dotenv-rails"

# 認証系
gem "devise"
gem "devise-i18n"
gem "devise_token_auth"

# OmniAuth Authentication
gem "omniauth"
gem "omniauth-facebook"
gem "omniauth-github"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"

# レスポンスJSONを制御
gem "active_model_serializers"

# stripe
gem "stripe", "9.1.0"

group :development, :test do
  # テスト用データを簡単に作成する
  gem "factory_bot_rails"
  gem "faker"

  # intelliSenseを使えるようにする
  gem "solargraph"

  gem "letter_opener_web"

  # pryを使えるようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワークrspecを導入
  gem "rspec-rails"

  # rubocopを導入
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"

  gem "solargraph"
end
