source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.3.3"

# rails本体（標準gem）
gem "rails", "~> 7.0.8", ">= 7.0.8.4"

# MySQLに接続するためのgem
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem） [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

gem 'net-protocol', '~> 0.2.2'
gem 'net-pop', '~> 0.1.2'

group :development, :test do
  # pryを使えるようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワークrspecを導入
  gem "rspec-rails"

  # rubocopを導入
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
